In [1]:
import numpy as np

In [8]:
array1= np.array([1,2,3,4])

In [9]:
array1.dtype

dtype('int64')

In [10]:
np.size(array1)

4

In [11]:
np.shape(array1)

(4,)

In [12]:
np.ndim(array1)

1

In [13]:
array2=([[1,2,6,7],
         [4,3,9,5]])

In [14]:
array3= ([[[7,5,14],[21,8,11]],
           [[8,6,20],[14,3,9]]])

In [15]:
np.size(array2)

8

In [16]:
np.ndim(array2)

2

In [17]:
np.shape(array2)

(2, 4)

In [18]:
np.size(array3)

12

In [20]:
np.ndim(array3)

3

In [21]:
np.shape(array3)

(2, 2, 3)

In [25]:
array2[0:2]

[[1, 2, 6, 7], [4, 3, 9, 5]]

In [28]:
array2[0:6]

[[1, 2, 6, 7], [4, 3, 9, 5]]

In [32]:
array2[0:1]

[[1, 2, 6, 7]]

In [42]:
array2[0:8]

[[1, 2, 6, 7], [4, 3, 9, 5]]

In [41]:
array3[0:9]

[[[7, 5, 14], [21, 8, 11]], [[8, 6, 20], [14, 3, 9]]]

In [49]:
array2= np.array([[1,2,6,7],
                  [4,3,9,5]])
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [50]:
array2[0,3]

np.int64(7)

In [51]:
array2[0,1]

np.int64(2)

In [55]:
array2[0,1:3]

array([2, 6])

In [57]:
array2[1,1:4]

array([3, 9, 5])

In [52]:
array3= np.array([[[7,5,14],[21,8,11]],
                  [[8,6,20],[14,3,9]]])
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [53]:
array3[1,1,2]

np.int64(9)

In [54]:
array3[0,0,1]

np.int64(5)

In [59]:
array3[0,1,0:3]

array([21,  8, 11])

In [60]:
array3[1,0,1:3]

array([ 6, 20])

In [65]:
a=np.zeros((5,3),dtype="int")
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [66]:
b=np.ones((5,3),dtype="int")
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
np.concatenate([a,b])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])